import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from '@/contexts/AuthContext';

import { UserProvider } from '@/contexts/UserContext'

import { BankAccountsProvider } from '@/contexts/BankAccountsContext';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <AuthProvider>
          <UserProvider>
            <BankAccountsProvider>
             {children}
            </BankAccountsProvider>
          </UserProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
